export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGIN_SUBMITTED = "LOGIN_SUBMITTED";

export default {
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    LOGIN_SUBMITTED,

};
