export const CHECK_USERNAME_EXISTS = "CHECK_USERNAME_EXISTS";
export const CHECK_EMAIL_EXISTS = "CHECK_EMAIL_EXISTS";
export const PASSWORDS_MATCH = "PASSWORDS_MATCH";
export const SUBMIT_FORM = "SUBMIT_FORM";
export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";
export const REGISTRATION_FAILED = "REGISTRATION_FAILED";
export const USERNAME_EXISTS = "USERNAME_EXISTS";
export const EMAIL_EXISTS = "EMAIL_EXISTS";
export const UPDATE_FORM_STATE = "UPDATE_FORM_STATE"
export default {
    CHECK_USERNAME_EXISTS,
    CHECK_EMAIL_EXISTS,
    USERNAME_EXISTS,
    EMAIL_EXISTS,
    PASSWORDS_MATCH,
    SUBMIT_FORM,
    REGISTRATION_SUCCESS,
    REGISTRATION_FAILED,
    UPDATE_FORM_STATE
};
